version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.6
    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "45:d8:81:51:95:7c:48:0a:7c:61:7b:d8:71:58:03:57"    

      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # cache the app data
      - run:
          name: cache app data
          command: |
            . venv/bin/activate
            python cache_app_data.py

workflows:
  version: 2
  hourly:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "7 * * * *"
          filters:
            branches:
              only:
                - master
